### ISSUE TITLE
Bad AddData response: 408 Session Proxy Timeout.

### ISSUE THREAD

**Issue by mnvx** [yandex/speechkitcloud#32]
Пытаюсь перевести в текст видео в режиме эмуляции передачи данных в реальном времени. Размер файла 21 МБ. Продолжительность 7 минут.
Вот сама [запись](https://www.youtube.com/watch?v=wGtVX56gvTY), которая была [скачена](http://ru.savefrom.net/#url=http://youtube.com/watch?v=wGtVX56gvTY) в формате MP4 360p.

Процесс распознавания не доходит до конца и обрывается ошибкой примерно на 5-й минуте

```
check result exception
<class 'asrclient.client.ServerError'>
Bad AddData response: 408 Session Proxy Timeout.
INFO:asrclient:future not running!
INFO:asrclient:Bad AddData response: 408 Session Proxy Timeout.
```

Вот более полный лог

```bash
$ asrclient-cli.py --realtime --model=queries --key=мой_ключ video.mp4
INFO:asrclient:uuid=4ea036b64bc446ae916476ba2cbaca18
INFO:asrclient:Connected to asr.yandex.net:80.
INFO:asrclient:session_id=3386fade-4525-11e7-9206-5ad957b9356d
INFO:asrclient:Recognition was started.
INFO:asrclient:About to send chunk 0 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 0, chunks answered 0
INFO:asrclient:got response: endOfUtt=False; len(recognition)=0; messages_count=1
INFO:asrclient:About to send chunk 1 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 0, chunks answered 1
INFO:asrclient:got response: endOfUtt=False; len(recognition)=0; messages_count=1
... вырезал кусок лога
INFO:asrclient:About to send chunk 290 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 0, chunks answered 290
INFO:asrclient:got response: endOfUtt=False; len(recognition)=0; messages_count=1
INFO:asrclient:About to send chunk 291 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 0, chunks answered 291
INFO:asrclient:got response: endOfUtt=False; len(recognition)=0; messages_count=1
INFO:asrclient:About to send chunk 292 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 0, chunks answered 292
INFO:asrclient:got response: endOfUtt=False; len(recognition)=0; messages_count=1
INFO:asrclient:About to send chunk 293 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 0, chunks answered 293
INFO:asrclient:About to send chunk 294 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 1, chunks answered 293
INFO:asrclient:About to send chunk 295 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 2, chunks answered 293
INFO:asrclient:About to send chunk 296 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 3, chunks answered 293
INFO:asrclient:About to send chunk 297 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 4, chunks answered 293
INFO:asrclient:About to send chunk 298 (65536 bytes)
INFO:asrclient:entering send() :start index 0, pending answers 5, chunks answered 293
check result exception
<class 'asrclient.client.ServerError'>
Bad AddData response: 408 Session Proxy Timeout.
INFO:asrclient:future not running!
INFO:asrclient:Bad AddData response: 408 Session Proxy Timeout.
Traceback (most recent call last):
  File "/usr/local/bin/asrclient-cli.py", line 134, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/asrclient-cli.py", line 131, in main
    **kwars)
  File "/usr/local/lib/python2.7/dist-packages/asrclient/client.py", line 420, in recognize
    onError(future.exception())
NameError: global name 'future' is not defined
```

Тут видно, что перед ошибкой почему-то несколько раз подряд вывелось `chunks answered 293`.

Подскажите, в случае распознавания текста из радио и теле трансляций в режиме реального времени будут действовать таймауты? 

И приспособлена ли система SpeechKit Cloud к решению этой задачи (распознавание текста из радио и теле трансляций)?

**Comment by krasilnikoff** [comment]
Nikolay, получилось ли "победить" ошибку, описанную выше?

**Comment by mnvx** [comment]
Если запускать без эмуляции реального времени, то работало хорошо. С эмуляцией победить не удалось. До "боевого" использование системы пока дело не дошло. Возникает ли проблема при боевом использовании, мне не известно.

**Comment by Mega4alik** [comment]
@mnvx Добрый день! Столкнулся с такой же проблемой. Скажите, удалось ли исправить ошибку? Заранее Спасибо

**Comment by mnvx** [comment]
@Mega4alik см. предыдущий мой комментарий. С тех пор пока не экспериментировал. Попробуйте без эмуляции.
